
dist: trusty

addons:
  sonarcloud:
    organization: "cs3250team4"
    token: "X8iPREsIPp5/+ObLz0OU1Mu/ZQPZl3sGISABx3iFDjbP505c9n78ehvWxm3b9WwROF0cx1I7xy8mXc1Zd/enthesIwStxufqNtSZ5buYVLGg3JetzFTI9gprmPs+/xY2fFXTnv6H6Iv1HyTRkdrKUYleq0mJPkwDDmqshMeQfrgczz1lydh+I0Es+rebdwtzmCLB6K6l+RqpmU+Wxxr/Uq2mFKhCen+YxupEEr7uhtIAKv/Dvk6I/J9LLiVwWN4jEvvtLdn14Jqm6ZzrHMc78fQvz/KQAbI31z2cojYaDQG1PYv2YQc7ss9oYeS9NIPzGwu8peBJVWU+yaDh+ROH9PmKKUVYITEoZVNIq1BXagMl36eX6FCKiarmJtFyfKNLQS5C9UxbnmgKUbR9+qAtCJjyMZf2yZll3r7pyYQA4gXfpSEh1oopFAHIEfIlK/xFvc6+OC5J0XRhuBULZR2jNqKq9Tam71rcbi2IGt56UEjdGxT7hmmwoMqOTG+IplGc3GB0Ho5zF9pPyZA4WJU32ASWgy/m1CO6I4WIsnOS7yZuWJOPJFdPuiBD/jZCyEa6u5wXgDlKd+gB/I3rqyiGK6mbpQjLYyFOs77M9fGNT+r1PAgOO7CxAW8AGja+MgLu40KxQnQ2hYWtMKl85A/nE2WQyaAKrbHHx/rQGbcpC5A="

script:
  - sonar-scanner -X

