language: python
python: 
  - "3.6"
cache: pip
install: 
  - pip install -r requirements.txt

dist: trusty

addons:
  sonarcloud:
    organization: "cs3250team4"
    token:
      secure: "UN2I23gRwkH0lBcdLGL6uOhqhVaEciuAYhd7gj3ukKuipd7/e6G9SkEvKfaGNcFUW9EF1z3oYiDVOAJqSrD1+tBoQpl16d3kkETt6UST8X50ctBncrGu+ixUI9FznQYwgYX4M1wTT14JCxM2cpH+2CvXy3AGG1fUo/y807nDHlfO3ktG/MLcdXeEwkQL8zZga73crL0EF47JW3vUXYESW9HgTR78k47ZaatkB0rDmr1v6qOB+25gR5G40mxPManMh2nfZRXSU8sD01O1kUgzb9gjhRS+3F/TfZEWdGgj5hRzkMy86/V7/32hmhlDaJarE4tRdtGvxcJl6IXxH1s6QXT44lRaMKMNGSsimdBxac9T/eY2sSw2b0WVJqmgFpuYQ2QLPPlMdUtFXgnigP+3I/UUc1SkGLQa+GoTY085wpiLmKcdGnqtqw/3XM/uiUbjpXwb+jNMUp3eMywaPyGr4GxCjjubSk0dW0YqCa0T8+r6hyC59v1pFTT6Bw4bMYGthI7YghCIn/kdHHkzVwkKCJeWE/NhDc15rQH76yly8qH4/TTlvqMxBlc/anZbKRw656EPP71xEGE078KZklGc8UTMTAxT/exTVCAh6TvkjgfLPMCi1WH93PLF12I+7r+ul7vHCQYs271GhVthQFL5pk/8mIJmjdJjEC1r/OCXLu8="

script:
  - sonar-scanner
  - pytest
