
language: python
python:
  - "3.7"
  - "3.8"
cache: pip
install:
  - pip install -r requirements.txt


addons:
  sonarcloud:
    organization: "cs3250team4"
    token:
      secure: "b5b4carfWnZ2gqpBkHxp4PUPYnjwW5eu4C7HqSNdTsYOYRKvJcMbxpF43c10aDCeT6JYMsYXXZv/NZ7D0bOiPu+r4BXDFo8uCMMQc9q99GigbMO9KApZzkz8Q1HDdduipXGFFaURJY7IY2N1wcO3ZcN6AmK9Gmq/9PvvSsJSiPqyPztUGZeIxxbx/WTYiw+36Y7guDvaioIkV8lZ3IPf+96FF7qbRLyl03QxArQDwk5JrBUG1NhRx6vYf3iXvsdLDurDHXDp/umTOOFjaZPiCdoRjaPIWBl+XxEPQXgMewe289zcJZbR+J5Kw5ninrxDy8SVvPk+B6pm0SmWlbF7QtuqUwMbjnIBoAmHBZ6SjFnPpG/xC2XuL6lGRFiDO4wYxrD3sxR7r4VnRUGQz84M3sOa8G6PG6fyrHbbW/xuCaJBbejGxGAzXLfeHqEW+WYoFELZ+mi2vt99tl+sFC3NWKndKv/PQnd1f/V/+JP5yTBmiBb5MbihSDRo6L8treLezh99DdvHDJUqhf1RaGuso0VKqA/CTkoibIUZVRWNSLiOok6xx61l3H8RF5Y9JBG5IjItrfU+bgL6FfAoEORC0HMibVdgT5oFy+BDo90ngw1VPRMsBOHS/rY1FaF3d+rGyu7+R0y7nXyP9fvHgQypBg9zYI2wuSWnPYBo5DGjyzM="

script:
  - sonar-scanner

# Uncomment to run tests (no tests yet)
#script:
#  - pytest